### ISSUE TITLE
Get rid of SlashTHEM

### ISSUE THREAD

**Issue by mathematicalcoffee** [junethack/Junethack#50]
It's got some server-only bug meaning you can't really play a game for any length of time before it crashes repeatedly and unrecoverably.

```
<Soviet5lo> As for the crashes Bluescreen and a few others all collectively agree it's due to random corruption in mons[]
```

In one game I had, whenever I tried to wish the game would crash. I was told (by Bluescreen) that as I continued playing the game would get progressively more corrupted and eventually would not even load. The next time I logged on to continue the game (I was going to die creatively), it had disappeared off the server completely and was not logged as part of Junethack. The game was not able to be recovered.

In the second game, I played as a doppelganger monk, but whenever I #youpoly, the game would crash. Hard to be a doppelganger who can't poly! Same bug, apparently. At least this time I was able to die before the game disappeared off the server, so as to have my achievements recorded for Junethack.

Anyhow, a game that is broken (not in terms of being too hard, but in terms of instability and crashes) should not be part of Junethack. 

I would argue that it even be removed this month (how can I ascend in every variant when you cannot ascend in SlashTHEM because of corruption bugs? though let's be honest, I'm not going to ascend in every variant anyway). However, I do understand that many players have devoted time to it already(e.g. it's great for unique deaths simply due to the large number of monsters), and to remove SlashTHEM half way through the month would waste that time, so probably best to leave it in this year.

**Comment by mathematicalcoffee** [comment]
Perhaps a compromise for this year is to remove it from the "ascend in all variants" (and maybe "medusa in all variants") trophies (since usually it's corrupted by the time you get that far), but include it for everything else?

**Comment by bhaak** [comment]
That's one of the risks when you use variants that are in development and are not fully tested. We had in earlier years also problems with disappearing servers or buggy variants.

For what it's worth, the crash bug has been located and a workaround has been deployed on nethack.xd.cm.

**Comment by bhaak** [comment]
SlashTHEM is currently no longer in Junethack. Haven't received any complaints about that. :-)
