### ISSUE TITLE
SLEX trophies, version 2.70

### ISSUE THREAD

**Issue by AmyBSOD** [junethack/Junethack#64]
[slextrophies2021.zip](https://github.com/junethack/Junethack/files/6304116/slextrophies2021.zip)

This adds new trophies for SLASH'EM Extended 2.70, which are encoded in the achieveX xlogfile string. The new trophies are:
devnull_complete = s-devnull.png "visited all DevNull challenges"
killed_minotaur = s-minotaur.png "killed the Minotaur of the Maze"
killed_kalwina = s-kalwina.png "killed Kalwina"
killed_stahngnir = s-stahngnir.png "killed Lord Stahngnir"
killed_ariane = s-ariane.png "killed Lady Ariane"
completed_rivalquest = s-rivalquest.png "completed the Rival Quest"
completed_minusworld = s-minusworld.png "completed the Minus World"
killed_vera = s-vera.png "killed Vera the Ice Queen"
killed_elaine = s-elaine.png "killed Elaine the Enchantress"

On the Junethack trophies page for SLEX, please sort them such that the ones that aren't for killing specific monsters are sorted with the other misc trophies (imbued bell of opening, imbued amulet of yendor etc.) :-)

**Comment by bhaak** [comment]
Added in 951090a386e88e72230bc40a11ce627080aa4a4a
