### ISSUE TITLE
dNethack trophy names and new trophies

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [junethack/Junethack#70]
Link to CSV: https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/compat-3.21.0/junethack_trophies/trophy_descriptions.csv

dNethack has one new role this year: the Madman (file code "Mad"), which will need to be added to the dNethack Tour trophy (I'm going to create a second suggesting the removal of the dNethack prince and king trophies, the tour one I kind of like the idea of).

All trophies now have names listed (which is clearly the important part, not the artwork <_<). I've separated out the new trophies from the old ones.

The first three trophies are straightforward achieveX tags, the first for finishing the Madman quest, the other two for defeating Lamashtu and Baalphegor (it seemed odd that Demogorgon and Asmodeus had trophies but those two didn't).

The last pair of trophies is a bit more complex, but I think still straightforward to add. There is a set of three _vault achieveX tags, and I'm proposing giving out the first trophy when a player earns any one of those tags, and the second trophy once a player has earned all three of those tags (across however many games that takes). If that's not actually straightforward to handle, there could just as easily be one trophy per _vault flag.

**Comment by bhaak** [comment]
Oops. Forgot to close this one. Should be working with e26fc77ec4ffb870030dd6ac2c2e360e8fba9ac0
