### ISSUE TITLE
Remove dNethack Prince and King trophies

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [junethack/Junethack#71]
dNethack is the only variant with its own Prince and King trophies. While they served at least a theoretical purpose originally, they're now largely redundant with the per-role quest trophies and per-race ascension trophies, have been getting more difficult to earn with each passing year, and require special handling to award. They were also not earned last year, and have either never or almost never been earned.

Although basically all of those points apply to the dNethack Tour trophy, I still like it in theory because it doesn't require making it to the mid-to-late game. However, I would understand if you also dropped support for dNethack Tour. The bit where it's rarely-to-never actually earned certainly suggests that it serves no purpose.

**Comment by bhaak** [comment]
Done in 1111c4f4b55f78837f78a4c8fcfa4d0015f299bb
