### ISSUE TITLE
New trophies for EvilHack 0.8.2

### ISSUE THREAD

**Issue by k21971** [junethack/Junethack#91]
Trophy for defeating a new unique boss - Saint Michael (appears in purgatory, bright magenta boss Angel). In the xlogfile, will show up under 'killed_uniques' as 'Saint Michael'. Can use https://junethack.net/icons/m-astral.png as the icon, color could probably be bright magenta.

Trophy for entering Purgatory, shows up under achieveX as 'entered_purgatory'. Can use https://junethack.net/icons/c-highest-score.png as the icon, whatever color change makes sense.

Trophy for defeating another unique, Gollum. Shows under 'killed_uniques' as 'Gollum'. Can use https://junethack.net/icons/entered_the_gnomish_mines.png as the icon, maybe shade it light gray.

EDIT - this graphic https://junethack.net/icons/entered_moria.png recolored to bright magenta would be a great replacement for the goblin king glyph.

Thanks!

**Comment by david-loffredo** [comment]
Behold my five minute gollum image.   Might be better than just pallet swapping to gray.

![golumn](https://github.com/junethack/Junethack/assets/8879578/a6911d84-c7fb-498a-a6a7-1a28cbf56e20)

**Comment by david-loffredo** [comment]
How about this?

![golumn2](https://github.com/junethack/Junethack/assets/8879578/f220d8b6-290d-464a-8f3c-02470e809c26)

**Comment by k21971** [comment]
Perfect.

**Comment by copperwater** [comment]
Since when is Gollum a gnome?

**Comment by k21971** [comment]
G for Gollum. Plus there's several 'h' trophies already for the Riders' horses.
