### ISSUE TITLE
validates_format_of regular expressions validation intention can be bypassed by line feeds

### ISSUE THREAD

**Issue by demogorgon22** [junethack/Junethack#94]
I was able to register a clan with just the value %0a and it went through, I then found I could register a user named `A%0a<h1>HI</h1>`.
Discussion on IRC suggests using `\z` instead of `$`, as the regular expression handling by ruby will match a line feed as `$`, which is undesirable behavior in these cases.

```http
POST /create HTTP/2
Host: junethack.net
Cookie: rack.session=f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2
Content-Length: 94
Cache-Control: max-age=0
Sec-Ch-Ua: "Not-A.Brand";v="99", "Chromium";v="124"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Windows"
Upgrade-Insecure-Requests: 1
Origin: https://junethack.net
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.6367.118 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: https://junethack.net/register
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Priority: u=0, i

username=A%0a<h1>HI</h1>&password=blahexample%21&confirm=blahexample%21&submit=Register%21
```
It's unclear without further research what the impacts of being able to bypass these filters are, but it can probably get pretty nasty, so this is probably a high priority fix.
https://github.com/junethack/Junethack/blob/a95f8a522c56cac640a1440c183a12f126e21358/lib/junethack/models/user.rb#L26

**Comment by markhallutah** [comment]
"as long as you're in there" please add period or dot (.) as a valid char in clan name and perhaps user name.
